# Cloudflare 相关配置，请自行修改
Cloudflare_Zone_ID=""       # type in zoneID
Cloudflare_API_Tokens=""    # type in token
Domain_Record=""            # ddns.example.com

# IP API 地址
api_v4="https://ipv4.ddnsip.cn"
api_v6="https://ipv6.ddnsip.cn"

# 网关地址
gateway='192.168.0.1'

# cloudflare 重连计数
retry_limit=10

# 脚本启动延迟时间
start_delay=120

# 是否使用IPv6临时地址(bool: true/false)
ipv6_temporary=true

# 是否尝试重新判断公网IPv6(bool: true/false)
ipv6_detect_retry=true

# ip检查延时(秒)
ip_check_delay=180
