# Cloudflare 相关配置，请自行修改
Cloudflare_Zone_ID=""       # type in zoneID
Cloudflare_API_Tokens=""    # type in token
Domain_Record=""            # ddns.example.com

# 网关地址
gateway="192.168.0.1"

# 获取系统IP使用的网卡接口，为空则使用所有的网卡接口
# 使用 ip link / ip address 查看你的网卡接口
ipv4_nic=""
ipv6_nic=""

# cloudflare 重连计数
retry_limit=10

# 脚本启动延迟时间
start_delay=120

# 是否使用IPv6临时地址(bool: true/false)
ipv6_temporary=true

# 是否尝试重新判断公网IPv6(bool: true/false)
ipv6_detect_retry=true

# ip检查延时(秒)
ip_check_delay=180

# 单个 IP API 重试次数
ipapi_max_retries=3

# itdog api：cu_联通, cm_移动, ct_电信
# IPv4 API 列表
api_v4_list=(
    "https://ddnsip.cn/json"
    "https://ipv4_cm.itdog.cn/"
    "https://ipv4_ct.itdog.cn/"
    "https://ipv4_cu.itdog.cn/"
    "https://api.ip.sb/jsonip"
    "https://api64.ipify.org/?format=json"
    "https://ipinfo.io/"
)

# IPv6 API 列表
api_v6_list=(
    "https://ddnsip.cn/json"
    "https://ipv6_cm.itdog.cn/"
    "https://ipv6_ct.itdog.cn/"
    "https://ipv6_cu.itdog.cn/"
    "https://api.ip.sb/jsonip"
    "https://api64.ipify.org/?format=json"
    "https://6.ipinfo.io/"
)
